# Generated by Django 3.2.7 on 2021-09-22 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control_de_pendientes', '0002_auto_20210922_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending',
            name='user',
            field=models.ForeignKey(default='<django.db.models.query_utils.DeferredAttribute object at 0x000001CF0FA085B0> <django.db.models.query_utils.DeferredAttribute object at 0x000001CF0FA08610>', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
