# Generated by Django 3.2.7 on 2021-09-22 14:17

from django.conf import settings
import django.contrib.auth.base_user
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control_de_pendientes', '0003_alter_pending_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending',
            name='user',
            field=models.ForeignKey(default=django.contrib.auth.base_user.AbstractBaseUser.get_username, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
