# Generated by Django 3.2.7 on 2021-09-22 14:31

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control_de_pendientes', '0007_auto_20210922_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='pending',
            name='user',
            field=models.ForeignKey(default=django.contrib.auth.models.User, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
