# Generated by Django 3.2.7 on 2021-09-22 14:53

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control_de_pendientes', '0009_auto_20210922_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending',
            name='notice_number',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Número de aviso'),
        ),
        migrations.AlterField(
            model_name='pending',
            name='observations',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='pending',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='pending',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_de_pendientes.state', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pending',
            name='user',
            field=models.ForeignKey(default=django.contrib.auth.models.User, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reportado por'),
        ),
    ]
